#      ___ _           _     ___ _                            _
#     / __\ |__   __ _| |_  / __\ |__   __ _ _ __  _ __   ___| |___
#    / /  | '_ \ / _` | __|/ /  | '_ \ / _` | '_ \| '_ \ / _ \ / __|
#   / /___| | | | (_| | |_/ /___| | | | (_| | | | | | | |  __/ \__ \
#   \____/|_| |_|\__,_|\__\____/|_| |_|\__,_|_| |_|_| |_|\___|_|___/
#
## WARNING: Edit this file with caution... Changes made within this file will directly correlate to how the plugin operates
##          If the configuration file is breaking the plugin then delete the current file and a new one will generate

## Bundled Placeholders:
## - %color%        ::  The color specified in focused channel's properties  (The channel color)
## - %chatcolor%    ::  The color specified in focused channel's properties  (The color on the chat)
## - %identifier%   ::  The identifier specified in the focused channel's properties
## - %channel%      ::  The name of the channel specified in the focused channel's properties
## - %player%       ::  The name of the player sending the message
## - %message%      ::  The message being sent
## - *** PlaceholderAPI support allows you to use any custom placeholders you specify for your server ***

data:
  ## How do would you like channel loading to be handled?
  ##
  ## ------
  ## If you are utilizing a custom registry to suit your needs then substitute this value for the identifier
  ## or an alias you have specified in your registry constructor. For more information see the API documentation
  ## ------
  ##
  ## By default, the bundled strategy uses the config to define classes; "config", "configuration", or "simple" are acceptable values
  storage-strategy: "simple"
chat-settings:
  ## * This value will be parsed for placeholders. *
  ## * Color code supported *
  format: "&8[%color%%identifier%&8] %player%&7: %chatcolor%%message%"

  ## Do you want the player to be able to view the permission node for channels they cannot message in?
  ## Ex: "You need 'channel.donator.permission' to speak here!'
  announce-permissions: false

  ## Do you want messages sent in chats to be logged to console?
  log-messages: true
channels:
  # ****************************
  #   EXAMPLE CHANNEL LAYOUT
  # ****************************
  #
  #  demo:
  #    ## The name of the channel you are creating
  #    ## This value is displayed in most plugin messages
  #    ## If your name contains spaces users will have to replace them with '_' in their command
  #    ## Ex: "You have hidden Demo Channel"
  #    name: "Demo Channel"
  #
  #    ## The description of the channel
  #    ## This is only shown in select places in the plugin
  #    description: "A basic channel created for the purpose of demonstrating the plugin"
  #
  #    ## The short-hand code for the channel
  #    ## Usually a single character (e.g. "A", "B", "C", "STAFF")
  #    identifier: "D"
  #
  #    ## Aliases that can be used when running channel commands
  #    ## Primarily helpful when switching channels, (e.g. "/chat focus D")
  #    aliases:
  #      - "D"
  #      - "Test"
  #
  #    properties:
  #      ## The color of the channel, will be applied to all references to the channel
  #      color: "&7"
  #
  #      ## The color of the messages displayed in this channel
  #      chat-color: "&f"
  #
  #      ## The enforced delay between messages
  #      ## Measured in seconds
  #      cooldown: 1.0
  #
  #      ## How close must a player be to the sender for them to see their messages
  #      ## If this value is '-1' then this feature will be toggled off for this specific chat
  #      ## If toggled on, users will not be able to see channels across different worlds
  #      chat-radius: -1
  #
  #      ## The required permission level needed to chat/focus/view this channel
  #      ## If the permission node is "*" then all users will be able to interact with the channel
  #      permission: "*"
  #
  #      ## Should players automatically view this channel when they join the server?
  #      auto-view: true
  #
  #      ## Should players automatically focus on this channel when they join the server?
  #      ## Note: If this option is toggled for multiple channels then the user will be focued on whatever channel was processed last
  #      auto-focus: false
  #

  global:
    name: "Global"
    description: "A generic global chat"
    identifier: "G"
    aliases:
      - "G"
      - "Global"
    properties:
      color: "&f"
      chat-color: "&7"
      cooldown: 1.0
      chat-radius: -1
      permission: "*"
      auto-view: true
      auto-focus: true